# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.proto_pb2 as proto__pb2


class LlamaCallbackStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.llamaAsk = channel.unary_stream(
                '/proto.LlamaCallback/llamaAsk',
                request_serializer=proto__pb2.LlamaRequest.SerializeToString,
                response_deserializer=proto__pb2.LlamaReply.FromString,
                )


class LlamaCallbackServicer(object):
    """Missing associated documentation comment in .proto file."""

    def llamaAsk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlamaCallbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'llamaAsk': grpc.unary_stream_rpc_method_handler(
                    servicer.llamaAsk,
                    request_deserializer=proto__pb2.LlamaRequest.FromString,
                    response_serializer=proto__pb2.LlamaReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.LlamaCallback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LlamaCallback(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def llamaAsk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.LlamaCallback/llamaAsk',
            proto__pb2.LlamaRequest.SerializeToString,
            proto__pb2.LlamaReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
