# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\x12\x05proto\"\x1e\n\x0cLlamaRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1c\n\nLlamaReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2G\n\rLlamaCallback\x12\x36\n\x08llamaAsk\x12\x13.proto.LlamaRequest\x1a\x11.proto.LlamaReply\"\x00\x30\x01\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\007ex.grpc\242\002\003HSW'
  _globals['_LLAMAREQUEST']._serialized_start=22
  _globals['_LLAMAREQUEST']._serialized_end=52
  _globals['_LLAMAREPLY']._serialized_start=54
  _globals['_LLAMAREPLY']._serialized_end=82
  _globals['_LLAMACALLBACK']._serialized_start=84
  _globals['_LLAMACALLBACK']._serialized_end=155
# @@protoc_insertion_point(module_scope)
